### ISSUE TITLE
the correct way to install if you have windows

### ISSUE THREAD

**Issue by lior007** [magic-quill/MagicQuill#11]
1. clone: git clone --recursive https://github.com/magic-quill/MagicQuill.git
2. cd MagicQuill
3. download the models: 
https://hkustconnect-my.sharepoint.com/:u:/g/personal/zliucz_connect_ust_hk/EWlGF0WfawJIrJ1Hn85_-3gB0MtwImAnYeWXuleVQcukMg?e=Gcjugg&download=1
4. unzip

or clone from huggingface : git clone https://huggingface.co/LiuZichen/MagicQuill-models
and then: 

# forward slashes
New-Item -Path "models/brushnet/random_mask_brushnet_ckpt" -ItemType Directory -Force
New-Item -Path "models/brushnet/segmentation_mask_brushnet_ckpt" -ItemType Directory -Force

# Copy-Item
Copy-Item "models/inpaint/brushnet/random_mask_brushnet_ckpt/diffusion_pytorch_model.safetensors" "models/brushnet/random_mask_brushnet_ckpt/"
Copy-Item "models/inpaint/brushnet/segmentation_mask_brushnet_ckpt/diffusion_pytorch_model.safetensors" "models/brushnet/segmentation_mask_brushnet_ckpt/"

5. open brushnet_nodes.py with editor (MagicQuill\MagicQuill\brushnet_nodes.py)
replace this line: 
brushnet_file = os.path.join(self.inpaint_files[brushnet], brushnet)
with:
brushnet = brushnet.replace('/', '\\')
brushnet_file = os.path.join(self.inpaint_files[brushnet], brushnet)

6. create environment: conda create -n MagicQuill python=3.10 -y
7. activate: conda activate MagicQuill
8. pip install gradio_magicquill-0.0.1-py3-none-any.whl
9. copy pyproject.toml MagicQuill\LLaVA\
10. pip install -e MagicQuill/LLaVA/
11. pip install -r requirements.txt
12. open gradio_run.py with editor

replace this line: 
ckpt_name = gr.Dropdown(
    label="Base Model Name",
    choices=folder_paths.get_filename_list("checkpoints"),
    value='SD1.5/realisticVisionV60B1_v51VAE.safetensors',
    interactive=True
)

with: 
default_model = os.path.join('SD1.5', 'realisticVisionV60B1_v51VAE.safetensors')
ckpt_name = gr.Dropdown(
    label="Base Model Name",
    choices=folder_paths.get_filename_list("checkpoints"),
    value=default_model,
    interactive=True
)

replace this line: 
uvicorn.run(app, host="0.0.0.0", port=7860)
with: 
uvicorn.run(app, host="127.0.0.1", port=7860)

13. $env:CUDA_VISIBLE_DEVICES=0; python gradio_run.py

IF YOU GET ERROR (when you do: $env:CUDA_VISIBLE_DEVICES=0; python gradio_run.py)
You may have installed a version of PyTorch without CUDA support. This sometimes happens when installing via pip install -r requirements.txt - a default version of PyTorch that does not include GPU support is installed

so do that:

14. pip uninstall torch torchvision torchaudio
15. pip install torch==2.1.2 torchvision==0.16.2 --index-url https://download.pytorch.org/whl/cu121
16. pip install -r requirements.txt --upgrade
17. $env:CUDA_VISIBLE_DEVICES=0; python gradio_run.py

**Comment by zliucz** [comment]
Hi, there. Thank you very much for taking the time to document the Windows setup process! :)

We primarily tested MagicQuill on Linux environments, so your contribution regarding Windows compatibility is very valuable. We'll incorporate your findings into readme and see how we can modify the code to help other Windows users.

**Comment by lior007** [comment]
> Hi, there. Thank you very much for taking the time to document the Windows setup process! :)
> 
> We primarily tested MagicQuill on Linux environments, so your contribution regarding Windows compatibility is very valuable. We'll incorporate your findings into readme and see how we can modify the code to help other Windows users.

thank you
i add another line just now
.its work fine !!!
thank you

**Comment by ap-chehov** [comment]
(MagicQuill) F:\MagicQuill>$env:CUDA_VISIBLE_DEVICES=0; python gradio_run.py
The filename, directory name, or volume label syntax is incorrect

**Comment by Aenon1** [comment]
I keep getting this when running gradio:
(venv) PS D:\Ai\MagicQuill> $env:CUDA_VISIBLE_DEVICES=0; python gradio_run.py
Traceback (most recent call last):
  File "D:\Ai\MagicQuill\gradio_run.py", line 17, in <module>
    from MagicQuill.scribble_color_edit import ScribbleColorEditModel
  File "D:\Ai\MagicQuill\MagicQuill\scribble_color_edit.py", line 9, in <module>
    from .brushnet_nodes import BrushNetLoader, BrushNet, BlendInpaint, get_files_with_extension
  File "D:\Ai\MagicQuill\MagicQuill\brushnet_nodes.py", line 57
    brushnet = brushnet.replace('/', '\')
                                                      ^
SyntaxError: unterminated string literal (detected at line 57)
In case the formatting doesn't work in the post, here is a screen shot.
![{0862AE84-BBF9-4BAD-953D-B5920212CEF7}](https://github.com/user-attachments/assets/b80fa934-ba4f-40da-b5cb-38e8a7911dd4)

**Comment by z-jin-1** [comment]
I apologize for the new issue I encountered while using it. I uploaded images and inputted my requirements, then sent the "run" command, but the page displayed an error.：Connection errored out。
The error message in the background is as follows:：
···
···
···
INFO:     127.0.0.1:62009 - "GET /assets/Index-8a960a35.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:62018 - "GET /assets/Index-88b18a9f.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:62029 - "GET /assets/api-logo-5346f193.svg HTTP/1.1" 200 OK
INFO:     127.0.0.1:62010 - "GET /assets/Example-4dcb2d09.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:62028 - "GET /assets/logo-3707f936.svg HTTP/1.1" 200 OK
INFO:     127.0.0.1:62009 - "GET /custom_component/dbef9011048921150f1209e4e74cf839/component/index.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:62009 - "GET /favicon.ico HTTP/1.1" 200 OK
INFO:     127.0.0.1:62604 - "POST /magic_quill/process_background_img HTTP/1.1" 200 OK
INFO:     127.0.0.1:62605 - "POST /queue/join HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\project\pythonVenv\MagicQuill\lib\site-packages\pydantic\type_adapter.py", line 270, in _init_core_attrs
    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
  File "D:\project\pythonVenv\MagicQuill\lib\site-packages\pydantic\type_adapter.py", line 112, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

error is：pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type


Before the system runs：
![image](https://github.com/user-attachments/assets/d697508c-b884-4fa2-8e49-79387d646151)

After the system is up and running：
![image](https://github.com/user-attachments/assets/d3bf2837-1eec-4043-bec6-1fa0789db9fd)

ERROR:

![image](https://github.com/user-attachments/assets/87350b8d-2607-44af-94c8-6615f48938ef)

![image](https://github.com/user-attachments/assets/7442beb6-5f7f-4a1d-a56d-ed30c7f13c2a)

**Comment by bmadgett** [comment]
Make the line 57 of brushnet_nodes.py instead:
brushnet = brushnet.replace('/','\\')

**Comment by Rokkonrol** [comment]
Thanks for the guide. The only thing I would change is the line from Step 5 that @bmadgett mentioned above.

**Comment by Vadimus666** [comment]
ValueError: You can't pass `load_in_4bit`or `load_in_8bit` as a kwarg when passing `quantization_config` argument at the same time.

**Comment by yitao2020** [comment]
5.pip install -e MagicQuill/LLaVA/      

D:\MagicQuill>pip install -e MagicQuill/LLaVA/
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///D:/MagicQuill/MagicQuill/LLaVA
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
INFO: pip is looking at multiple versions of llava to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement torch==2.1.2 (from llava) (from versions: 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0, 2.4.1, 2.5.0, 2.5.1)
ERROR: No matching distribution found for torch==2.1.2

I encountered the problem that I couldn't find TORCH = 2.1.2

**Comment by TacImpulse** [comment]
Anyone else getting only an 8kb completely blank .PNG file every time you finish editing an image, then Right Click & Save As... on Windows 11? If so, got a workaround?

**Comment by Gex010** [comment]
What did I miss?

Traceback (most recent call last):
  File "C:\Users\weztr\Desktop\MagicQuill\gradio_run.py", line 19, in <module>
    llavaModel = LLaVAModel()
  File "C:\Users\weztr\Desktop\MagicQuill\MagicQuill\llava_new.py", line 26, in __init__
    self.tokenizer, self.model, self.image_processor, self.context_len = load_pretrained_model(
  File "C:\Users\weztr\Desktop\MagicQuill\MagicQuill\LLaVA\llava\model\builder.py", line 116, in load_pretrained_model
    tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)
  File "C:\Users\weztr\miniconda3\envs\MagicQuill\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 758, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "C:\Users\weztr\miniconda3\envs\MagicQuill\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 590, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "C:\Users\weztr\miniconda3\envs\MagicQuill\lib\site-packages\transformers\utils\hub.py", line 450, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: 'C:\Users\weztr\Desktop\MagicQuill\MagicQuill\../models/llava-v1.5-7b-finetune-clean'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

**Comment by Astroburner** [comment]
> What did I miss?
> 
> Traceback (most recent call last): File "C:\Users\weztr\Desktop\MagicQuill\gradio_run.py", line 19, in llavaModel = LLaVAModel() File "C:\Users\weztr\Desktop\MagicQuill\MagicQuill\llava_new.py", line 26, in **init** self.tokenizer, self.model, self.image_processor, self.context_len = load_pretrained_model( File "C:\Users\weztr\Desktop\MagicQuill\MagicQuill\LLaVA\llava\model\builder.py", line 116, in load_pretrained_model tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False) File "C:\Users\weztr\miniconda3\envs\MagicQuill\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 758, in from_pretrained tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs) File "C:\Users\weztr\miniconda3\envs\MagicQuill\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 590, in get_tokenizer_config resolved_config_file = cached_file( File "C:\Users\weztr\miniconda3\envs\MagicQuill\lib\site-packages\transformers\utils\hub.py", line 450, in cached_file raise EnvironmentError( OSError: Incorrect path_or_model_id: 'C:\Users\weztr\Desktop\MagicQuill\MagicQuill../models/llava-v1.5-7b-finetune-clean'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

Update Gradio_run.py: "llavaModel = LLaVAModel()" ->"llava_model_path = "E:/your_path_to_folder/llava-v1.5-7b-finetune-clean"

**Comment by addelh** [comment]
I'm receiving this error when I try to launch:

```
PS E:\magicquill> $env:CUDA_VISIBLE_DEVICES=0; python gradio_run.py
Traceback (most recent call last):
  File "E:\magicquill\gradio_run.py", line 16, in <module>
    from MagicQuill.llava_new import LLaVAModel
  File "E:\magicquill\MagicQuill\llava_new.py", line 10, in <module>
    from llava.conversation import conv_templates, SeparatorStyle
ModuleNotFoundError: No module named 'llava'
```

**Comment by dzbbdawang** [comment]
Traceback (most recent call last):
  File "C:\mofa_Draw\MagicQuill\gradio_run.py", line 20, in <module>
    scribbleColorEditModel = ScribbleColorEditModel()
  File "C:\mofa_Draw\MagicQuill\MagicQuill\scribble_color_edit.py", line 30, in __init__
    self.load_models('SD1.5', 'float16')
  File "C:\mofa_Draw\MagicQuill\MagicQuill\scribble_color_edit.py", line 43, in load_models
    self.brushnet = self.brushnet_loader.brushnet_loading(brushnet_name, dtype)[0]
  File "C:\mofa_Draw\MagicQuill\MagicQuill\brushnet_nodes.py", line 57, in brushnet_loading
    brushnet_file = os.path.join(self.inpaint_files[brushnet], brushnet)
KeyError: 'brushnet\\random_mask_brushnet_ckpt\\diffusion_pytorch_model.safetensors'

**Comment by nrkazmi** [comment]
I am getting this error. 
(MagicQuill) C:\Users\nraza\Desktop\MagicQuill>set CUDA_VISIBLE_DEVICES=0 && python gradio_run.py
Traceback (most recent call last):
  File "C:\Users\nraza\Desktop\MagicQuill\gradio_run.py", line 17, in <module>
    from MagicQuill.scribble_color_edit import ScribbleColorEditModel
  File "C:\Users\nraza\Desktop\MagicQuill\MagicQuill\scribble_color_edit.py", line 9, in <module>
    from .brushnet_nodes import BrushNetLoader, BrushNet, BlendInpaint, get_files_with_extension
  File "C:\Users\nraza\Desktop\MagicQuill\MagicQuill\brushnet_nodes.py", line 11, in <module>
    import comfy.sd
  File "C:\Users\nraza\Desktop\MagicQuill\MagicQuill\comfy\sd.py", line 5, in <module>
    from comfy import model_management
  File "C:\Users\nraza\Desktop\MagicQuill\MagicQuill\comfy\model_management.py", line 119, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "C:\Users\nraza\Desktop\MagicQuill\MagicQuill\comfy\model_management.py", line 88, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\Users\nraza\.conda\envs\MagicQuill\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "C:\Users\nraza\.conda\envs\MagicQuill\lib\site-packages\torch\cuda\__init__.py", line 289, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

(MagicQuill) C:\Users\nraza\Desktop\MagicQuill>


How to overcome this, please. any help

**Comment by foxtierney** [comment]
> I am getting this error on RUN
> line 199
> ckpt_name = gr.Dropdown
> ^
> IndentationError: unindent does not match any outer indentation level
@malc27 


Make sure your indentation looks like this. Python uses the indentation to organize which part of the program is grouped. If the indentation is wrong, (even with those parenthesis) then it might get confused.
![image](https://github.com/user-attachments/assets/84b5863b-34be-430e-8481-64c034597986)

**Comment by sumansaurabh** [comment]
will it work if I have no nvidia driver?

Iam getting this error:

```
  File "Q:\experimentsd\MagicQuill\gradio_run.py", line 17, in <module>
    from MagicQuill.scribble_color_edit import ScribbleColorEditModel
  File "Q:\experimentsd\MagicQuill\MagicQuill\scribble_color_edit.py", line 9, in <module>
    from .brushnet_nodes import BrushNetLoader, BrushNet, BlendInpaint, get_files_with_extension
  File "Q:\experimentsd\MagicQuill\MagicQuill\brushnet_nodes.py", line 11, in <module>
    import comfy.sd
  File "Q:\experimentsd\MagicQuill\MagicQuill\comfy\sd.py", line 5, in <module>
    from comfy import model_management
  File "Q:\experimentsd\MagicQuill\MagicQuill\comfy\model_management.py", line 119, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "Q:\experimentsd\MagicQuill\MagicQuill\comfy\model_management.py", line 88, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\Users\sumansaurabh\AppData\Local\anaconda3\envs\MagicQuill\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "C:\Users\sumansaurabh\AppData\Local\anaconda3\envs\MagicQuill\lib\site-packages\torch\cuda\__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```

**Comment by Vinzema369** [comment]
Traceback (most recent call last):
  File "C:\Users\KH\Desktop\MagicQuill\gradio_run.py", line 19, in <module>
    llavaModel = LLaVAModel()
  File "C:\Users\KH\Desktop\MagicQuill\MagicQuill\llava_new.py", line 26, in __init__
    self.tokenizer, self.model, self.image_processor, self.context_len = load_pretrained_model(
  File "C:\Users\KH\Desktop\MagicQuill\MagicQuill\LLaVA\llava\model\builder.py", line 117, in load_pretrained_model
    model = LlavaLlamaForCausalLM.from_pretrained(
  File "C:\ProgramData\miniconda3\envs\MagicQuill\lib\site-packages\transformers\modeling_utils.py", line 3790, in from_pretrained
    raise ValueError(
ValueError:
                        Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit
                        the quantized model. If you want to dispatch the model on the CPU or the disk while keeping
                        these modules in 32-bit, you need to set `load_in_8bit_fp32_cpu_offload=True` and pass a custom
                        `device_map` to `from_pretrained`. Check
                        https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu
                        for more details.
After I run set CUDA_VISIBLE_DEVICES=0 && python gradio_run.py , this error happed. Please kindly help me to solve it. Thanks

**Comment by PickausernamePi** [comment]
> # forward slashes
> 
> New-Item -Path "models/brushnet/random_mask_brushnet_ckpt" -ItemType Directory -Force New-Item -Path "models/brushnet/segmentation_mask_brushnet_ckpt" -ItemType Directory -Force

Hello, and thanks for the guide. Could you elaborate what this means?

**Comment by NicodemPL** [comment]
https://hkustconnect-my.sharepoint.com/:u:/g/personal/zliucz_connect_ust_hk/EWlGF0WfawJIrJ1Hn85_-3gB0MtwImAnYeWXuleVQcukMg?e=Gcjugg&download=1

is not available for download. where to find this?

**Comment by zliucz** [comment]
@NicodemPL 
Try download from [Huggingface Model Repo](https://huggingface.co/LiuZichen/MagicQuill-models). Thanks.

Meanwhile, I will close this issue page as I noticed that the issues reported on this page have been a bit diverged.

**Comment by Aheaded** [comment]
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 86.00 MiB. GPU 0 has a total capacity of 8.00 GiB of which 4.48 GiB is free. Of the allocated memory 2.30 GiB is allocated by PyTorch, and 142.69 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

I am getting this error on a MSI RTX 4060 OC. Plz help..

**Comment by JamesIV4** [comment]
Hi everyone, I had ChatGPT make some nice INSTALL.bat and RUN.bat files to help us Windows users out. I used venv instead of conda, as I find it more convenient.

INSTALL.bat
```
@echo off
:: Check if a virtual environment exists
if not exist venv (
    echo Creating virtual environment...
    python -m venv venv
)

:: Activate the virtual environment
call venv\Scripts\activate

:: Install the required interface package
echo Installing gradio_magicquill...
pip install gradio_magicquill-0.0.1-py3-none-any.whl

:: Install the llava environment
echo Setting up LLaVA environment...
if not exist MagicQuill\LLaVA (
    echo Directory MagicQuill\LLaVA does not exist. Ensure the folder structure is correct.
    exit /b 1
)
copy /y pyproject.toml MagicQuill\LLaVA\
pip install -e MagicQuill\LLaVA\

:: Install remaining dependencies
echo Installing additional requirements...
pip install -r requirements.txt

:: Run MagicQuill
echo Starting MagicQuill...
set CUDA_VISIBLE_DEVICES=0
python gradio_run.py || (
    echo Error: Failed to run MagicQuill.
    pause
    exit /b 1
)
```

RUN.bat
```
@echo off
:: Check if the virtual environment exists
if not exist venv (
    echo Error: Virtual environment not found. Please create run INSTALL.bat once.
    exit /b 1
)

:: Activate the virtual environment
call venv\Scripts\activate || (
    echo Error: Failed to activate the virtual environment. Ensure it is properly set up.
    exit /b 1
)

:: Run the Python script
echo Running MagicQuill...
set CUDA_VISIBLE_DEVICES=0
python gradio_run.py || (
    echo Error: Failed to run MagicQuill.
    pause
    exit /b 1
)
```

**Comment by aykido** [comment]
A big thank you to the creators of this tutorial. It was amazing! I followed the steps calmly, and everything went smoothly without any issues. The setup was seamless and everything installed perfectly. Thanks again for this fantastic guide!

(P.S. If you’re like me and tend to get distracted, you can make the process even smoother by breaking down the steps with ChatGPT. It really helps with following along without missing anything!)

**Comment by ap-chehov** [comment]
> RUN.bat

Running MagicQuill...
  File "F:\MagicQuill\gradio_run.py", line 205
    negative_prompt = gr.Textbox(
IndentationError: unexpected indent
Error: Failed to run MagicQuill.

**Comment by foxtierney** [comment]
> when i try to run this command
> 
> > $env:CUDA_VISIBLE_DEVICES=0; python gradio_run.py
> 
> then i got this error:
> 
> > The filename, directory name, or volume label syntax is incorrect.
> 
> i already replaced the line 57 of file `brushnet_nodes.py` with `brushnet = brushnet.replace('/','\\')`
@chnisar515 

I think that this error is just because of the `$env` part of the command, not the python. You can see it appear if you run that part by itself. I was [able to get around](https://github.com/magic-quill/MagicQuill/issues/11#issuecomment-2488568142) this problem by using MINGW instead of the normal CMD.exe. However, when using MINGW, the commands remain the same as they are in the main installation guide of this repo.

I think that this console can be installed along with Git. if you select this option in the installation process:
![image](https://github.com/user-attachments/assets/37e9a4d2-1695-4572-9bbe-1185f2f15845)

**Comment by bmadgett** [comment]
> when i try to run this command
> 
> > $env:CUDA_VISIBLE_DEVICES=0; python gradio_run.py
> 
> then i got this error:
> 
> > The filename, directory name, or volume label syntax is incorrect.
> 
> i already replaced the line 57 of file `brushnet_nodes.py` with `brushnet = brushnet.replace('/','\\')`

Run the commands in PowerShell prompt, not normal Cmd prompt.

**Comment by JamesIV4** [comment]
> > when i try to run this command
> > > $env:CUDA_VISIBLE_DEVICES=0; python gradio_run.py
> > 
> > 
> > then i got this error:
> > > The filename, directory name, or volume label syntax is incorrect.
> > 
> > 
> > i already replaced the line 57 of file `brushnet_nodes.py` with `brushnet = brushnet.replace('/','\\')`
> 
> Run the commands in PowerShell prompt, not normal Cmd prompt.

Try using the batch script I wrote a few comments above, that's taken care of there. You should only need the couple file fixes outlined in OP's post.

**Comment by Aheaded** [comment]
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 86.00 MiB. GPU 0 has a total capacity of 8.00 GiB of which 4.48 GiB is free. Of the allocated memory 2.30 GiB is allocated by PyTorch, and 142.69 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation. See documentation for Memory Management (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

I am getting this error on a MSI RTX 4060 OC. Plz help..!!!

**Comment by zliucz** [comment]
@Aheaded This implies you are running out of GPU memory. You may disable the Draw&Guess, which occupies 5GB, by commenting on the LLaVA-related code and only keeping the editing function.

**Comment by mjbandroid** [comment]
> Hi, there. Thank you very much for taking the time to document the Windows setup process! :)
> 
> We primarily tested MagicQuill on Linux environments, so your contribution regarding Windows compatibility is very valuable. We'll incorporate your findings into readme and see how we can modify the code to help other Windows users.



> Hi, there. Thank you very much for taking the time to document the Windows setup process! :)
> 
> We primarily tested MagicQuill on Linux environments, so your contribution regarding Windows compatibility is very valuable. We'll incorporate your findings into readme and see how we can modify the code to help other Windows users.

Sorry, not sorry, but maybe try testing and setting things up for Windows, not just Linux—which only holds about 6% of the market share. Most people with GPUs are running Windows 10.  

We want to use AI and run these models and codes on Windows. Linux is fine, but it’s frustrating enough having to cut, copy, paste, and rely on GPT or other tools just to figure out what we’re doing.  

It would be great to have Windows instructions for all projects with clear steps—not just for the C directory. Better yet, why not provide straightforward, one-click installers that handle everything in the background, even if it’s within a virtual environment?

**Comment by aliok222** [comment]
If someone can successfully install and make this work flawlessly on Windows, I’m offering a $1,000 reward. Let me know if you’re up for the challenge . enjoy

**Comment by foxtierney** [comment]
> If someone can successfully install and make this work flawlessly on Windows, I’m offering a $1,000 reward. Let me know if you’re up for the challenge . enjoy
@aliok222 

Haven't plenty of people already done this? I have it working on my system even with my RTX 3070Ti 8GB. I do have to keep the automatic prompting off and have to minimize the browser during generation to save a few hundred MB of VRAM, but remove, add, and recolor features are all working for me and only take 30-80s per operation. I just followed the above guide as far as I can tell.

**Comment by yitao2020** [comment]
> If someone can successfully install and make this work flawlessly on Windows, I’m offering a $1,000 reward. Let me know if you’re up for the challenge . enjoy

Hahahahaha, don't be impulsive. I know you want to satire this project. Some people have already started the integration package of 10 -person coins on other platforms. I suggest that the author should solve the bug deployed by Window as soon as possible.

**Comment by bruceyyu** [comment]
> If someone can successfully install and make this work flawlessly on Windows, I’m offering a $1,000 reward. Let me know if you’re up for the challenge . enjoy

Dear @aliok222 , MagicQuill is an open-source research project. We are making $0 from it and we are not interested in your award either. We are sorry that it didn’t meet your expectation, but please be respectful in the community.

**Comment by aykido** [comment]
> If someone can successfully install and make this work flawlessly on Windows, I’m offering a $1,000 reward. Let me know if you’re up for the challenge . enjoy

I would like to thank in advance the very valuable and highly intelligent entrepreneurs here who offer many of the software they have developed as open source to the service of humanity, and the software developer friends who still respond politely to imbeciles like this. I have no hesitation in getting banned after this answer, but please continue to support us without losing their motivation and please do not read the rest of this answer. 

Faggot up there pontificating with $1000, yes I'm telling you.
Damn, look at you son of a bitch, he's here pontificating for 1000 dollars for a job that he somehow can't run, that he can't do with his own system, his own imbecility. You bastard, if you find a dollar on the ground, you will pick it up and put it in your pocket, who knows, your breath smells of hunger, he is here giving out money like spoiled children. Sons of bitches like this make the lives of bartenders in bars, cashiers in markets, and waiters in restaurants miserable. Now turn that $1000 into dollars one by one and shove it up your ass. Cock-headed, adolescent-minded bastard!

**Comment by bruceyyu** [comment]
> > If someone can successfully install and make this work flawlessly on Windows, I’m offering a $1,000 reward. Let me know if you’re up for the challenge . enjoy
> 
> I would like to thank in advance the very valuable and highly intelligent entrepreneurs here who offer many of the software they have developed as open source to the service of humanity, and the software developer friends who still respond politely to imbeciles like this. I have no hesitation in getting banned after this answer, but please continue to support us without losing their motivation and please do not read the rest of this answer.
> 
> Faggot up there pontificating with $1000, yes I'm telling you. Damn, look at you son of a bitch, he's here pontificating for 1000 dollars for a job that he somehow can't run, that he can't do with his own system, his own imbecility. You bastard, if you find a dollar on the ground, you will pick it up and put it in your pocket, who knows, your breath smells of hunger, he is here giving out money like spoiled children. Sons of bitches like this make the lives of bartenders in bars, cashiers in markets, and waiters in restaurants miserable. Now turn that $1000 into dollars one by one and shove it up your ass. Cock-headed, adolescent-minded bastard!

@aykido man I feel so sorry for you. Using your dollars to get yourself educated would be a better choice 😇

**Comment by bruceyyu** [comment]
> > If someone can successfully install and make this work flawlessly on Windows, I’m offering a $1,000 reward. Let me know if you’re up for the challenge . enjoy
> 
> I would like to thank in advance the very valuable and highly intelligent entrepreneurs here who offer many of the software they have developed as open source to the service of humanity, and the software developer friends who still respond politely to imbeciles like this. I have no hesitation in getting banned after this answer, but please continue to support us without losing their motivation and please do not read the rest of this answer.
> 
> Faggot up there pontificating with $1000, yes I'm telling you. Damn, look at you son of a bitch, he's here pontificating for 1000 dollars for a job that he somehow can't run, that he can't do with his own system, his own imbecility. You bastard, if you find a dollar on the ground, you will pick it up and put it in your pocket, who knows, your breath smells of hunger, he is here giving out money like spoiled children. Sons of bitches like this make the lives of bartenders in bars, cashiers in markets, and waiters in restaurants miserable. Now turn that $1000 into dollars one by one and shove it up your ass. Cock-headed, adolescent-minded bastard!

@aykido please mind your word 😬
