### ISSUE TITLE
ADD SAVE BUTTON FOR THE PICTURE (for windows)

### ISSUE THREAD

**Issue by lior007** [magic-quill/MagicQuill#12]
open the file in editor: gradio_run.py

### **LEVEL 1**

**after the line:**
import io
**add this line:**
import time

### **LEVEL 2**

**befor this block:**
css = '''
.row {
    width: 90%;
    margin: auto;
}
footer {
    visibility: 
    hidden
}
'''
**add this block:**
def save_generated_image(image_data):
    if image_data is None:
        return "No image to save"
    
    try:
        
        if isinstance(image_data, dict) and 'generated_image' in image_data.get('from_backend', {}):
            img_str = image_data['from_backend']['generated_image']
            if img_str.startswith("data:image/png;base64,"):
                img_str = img_str.split(",")[1]
            img_data = base64.b64decode(img_str)
            img = Image.open(io.BytesIO(img_data))
            
            os.makedirs("output", exist_ok=True)
            
            timestamp = time.strftime("%Y%m%d_%H%M%S")
            save_path = os.path.join("output", f"magicquill_{timestamp}.png")
            img.save(save_path)
            return f"Image saved to: {save_path}"
    except Exception as e:
        return f"Error saving image: {str(e)}"
    
    return "Failed to save image"

### **LEVEL 3**
**after the line:**
btn.click(generate_image_handler, inputs=[ms, ckpt_name, negative_prompt, fine_edge, grow_size, edge_strength, color_strength, inpaint_strength, seed, steps, cfg, sampler_name, scheduler], outputs=ms)
**add this line:**

        with gr.Row(elem_classes="row"):
            with gr.Column():
                save_btn = gr.Button("Save Image", variant="secondary")
                save_status = gr.Textbox(label="Save Status", interactive=False)

        
        save_btn.click(fn=save_generated_image, inputs=[ms], outputs=[save_status])

![save image](https://github.com/user-attachments/assets/e2d9b42b-3bc6-42d2-ab11-3490a30c78b4)

**Comment by zliucz** [comment]
Hi, there. Thank you for your excellent feature suggestion and sharing the implementation code! This will definitely make MagicQuill better :).

Would you consider submitting this as a pull request instead of an issue? This would make it easier for us to review, test, and integrate your code.
