### ISSUE TITLE
Why CC BY-NC 4.0 ?!?

### ISSUE THREAD

**Issue by thusinh1969** [magic-quill/MagicQuill#13]
Just out of curiousity ? Is there a paid version for self-commercialization ?

Steve

**Comment by zliucz** [comment]
Hi, Steve. Thank you for your interest.

MagicQuill is an open-source academic research project under CC BY-NC 4.0 license, which means it's not available for commercial use. We aim to foster innovation and knowledge sharing in the AI community rather than commercialization.
