### ISSUE TITLE
RuntimeError: No GPU found. A GPU is needed for quantization.

### ISSUE THREAD

**Issue by hongthana** [magic-quill/MagicQuill#15]
I tried to run this repo on MacBook Air M3. After calling `$ CUDA_VISIBLE_DEVICES=0 python gradio_run.py`, I received error as displayed below:

`
Total VRAM 24576 MB, total RAM 24576 MB
pytorch version: 2.1.2
Set vram state to: SHARED
Device: mps
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
/opt/anaconda3/envs/MagicQuill/lib/python3.10/site-packages/bitsandbytes/cextension.py:34: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
'NoneType' object has no attribute 'cadam32bit_grad_fp32'
.
.
.
/opt/anaconda3/envs/MagicQuill/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3030, in from_pretrained
raise RuntimeError("No GPU found. A GPU is needed for quantization.")
RuntimeError: No GPU found. A GPU is needed for quantization.
`

**Comment by bruceyyu** [comment]
@hongthana Hi thanks for your interest! Unfortunately, MagicQuill requires substantial GPU power to support image editing. If you want to use it on your laptop, please try our online demo on [huggingface](https://huggingface.co/spaces/AI4Editing/MagicQuill)
