### ISSUE TITLE
 No module named 'llava'

### ISSUE THREAD

**Issue by zachysaur** [magic-quill/MagicQuill#16]
(MagicQuill) D:\Q\New folder\MagicQuill-main>python gradio_run.py
Traceback (most recent call last):
  File "D:\Q\New folder\MagicQuill-main\gradio_run.py", line 16, in <module>
    from MagicQuill.llava_new import LLaVAModel
  File "D:\Q\New folder\MagicQuill-main\MagicQuill\llava_new.py", line 10, in <module>
    from llava.conversation import conv_templates, SeparatorStyle
ModuleNotFoundError: No module named 'llava'

(MagicQuill) D:\Q\New folder\MagicQuill-main>

**Comment by bruceyyu** [comment]
@zachysaur We are working on solving this issue on Windows. Meanwhile, please try this solution https://github.com/magic-quill/MagicQuill/issues/11

**Comment by zachysaur** [comment]
> @zachysaur We are working on solving this issue on Windows. Meanwhile, please try this solution #11

his solution causing more harm to it replacing it causing lines issues and in the end still same errors

**Comment by bruceyyu** [comment]
@zachysaur It's also possible that you missed "--recursive" command so that the whole llava submodule is missing

**Comment by zachysaur** [comment]
> @zachysaur It's also possible that you missed "--recursive" command so that the whole llava submodule is missing

i have used it tried every possible solution i made it run on google collab just face error when uploading picture it dont show up

**Comment by yardimli** [comment]
I would avoid spaces in path names "New folder" is always risky

**Comment by zachysaur** [comment]
> I would avoid spaces in path names "New folder" is always risky

i tried that to still same error

**Comment by z-jin-1** [comment]
Hello, I also encountered the same problem, windows running error said can not find the 'llava' module, I would like to consult you, the following is the details of the problem:

(MagicQuill) PS D:\project\pythonProject\MagicQuill> $env:CUDA_VISIBLE_DEVICES=0; D:\project\pythonVenv\MagicQuill\Scripts\python gradio_run.py
Traceback (most recent call last):
  File "D:\project\pythonProject\MagicQuill\gradio_run.py", line 18, in <module>
    from MagicQuill.llava_new import LLaVAModel
  File "D:\project\pythonProject\MagicQuill\MagicQuill\llava_new.py", line 10, in <module>
    from llava.conversation import conv_templates, SeparatorStyle
ModuleNotFoundError: No module named 'llava'



![Snipaste_2024-11-18_12-00-04](https://github.com/user-attachments/assets/0c08efdc-d45c-4411-9590-21310f385dca)
094)

**Comment by zliucz** [comment]
Hi, there. If you encounter the `ModuleNotFoundError: No module named 'llava' error`, this is likely due to incomplete repository initialization. Please follow these troubleshooting steps:

1. Verify LLaVA Submodule Installation
- Check if the LLaVA directory exists in your MagicQuill folder. 
- If the directory is empty or missing, the [Git LLaVA submodule](https://github.com/haotian-liu/LLaVA) wasn't properly initialized

2. Fix Submodule Initialization
- If you haven't cloned the repository yet:
`git clone --recursive https://github.com/magic-quill/MagicQuill.git`

- If you've already cloned without --recursive:
`git submodule init`
`git submodule update`

3. Environment Setup
- After confirming the LLaVA submodule is present, follow the environment setup instructions in the [setup guide](https://github.com/magic-quill/MagicQuill?tab=readme-ov-file#setup) (5th step). Make sure to complete all installation steps for the LLaVA dependencies.

This error typically occurs when the repository is cloned without the --recursive flag, causing the LLaVA submodule to be missing or incomplete. Following these steps should resolve the module import error.

**Comment by z-jin-1** [comment]
First of all, thank you very much. I solved the problem that I could not find the llava module according to the method you provided. Thank you very much again, but there is a new problem. But I can't find the problem, I hope you can help me out in your spare time, thank you very much!

(MagicQuill) PS D:\project\pythonProject\MagicQuill> $env:CUDA_VISIBLE_DEVICES=0; python gradio_run.py
Total VRAM 12287 MB, total RAM 40713 MB
pytorch version: 2.1.2+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : native
Using pytorch cross attention
['D:\\project\\pythonProject\\MagicQuill', 'D:\\pc\\python3.10.11\\python310.zip', 'D:\\pc\\python3.10.11\\DLLs', 'D:\\pc\\python3.10.11\\lib', 'D:\\pc\\python3.10.11', 'D:\\project\\pythonVenv\\MagicQuill', 'D:\\project\\pythonVenv\\MagicQuill\\lib\\site-packages', '__editable__.llava-1.2.2.post1.finder.__path_hook__', 'D:\\project\\pythonProject\\MagicQuill\\MagicQuill']
Traceback (most recent call last):
  File "D:\project\pythonVenv\MagicQuill\lib\site-packages\transformers\utils\hub.py", line 385, in cached_file
    resolved_file = hf_hub_download(
  File "D:\project\pythonVenv\MagicQuill\lib\site-packages\huggingface_hub\utils\_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "D:\project\pythonVenv\MagicQuill\lib\site-packages\huggingface_hub\utils\_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 'D:\project\pythonProject\MagicQuill\MagicQuill\../models/llava-v1.5-7b-finetune-clean'. Use `repo_type` argument if needed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\project\pythonProject\MagicQuill\gradio_run.py", line 19, in <module>
    llavaModel = LLaVAModel()
  File "D:\project\pythonProject\MagicQuill\MagicQuill\llava_new.py", line 26, in __init__
    self.tokenizer, self.model, self.image_processor, self.context_len = load_pretrained_model(
  File "D:\project\pythonProject\MagicQuill\MagicQuill\LLaVA\llava\model\builder.py", line 116, in load_pretrained_model
    tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)
  File "D:\project\pythonVenv\MagicQuill\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 758, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "D:\project\pythonVenv\MagicQuill\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 590, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "D:\project\pythonVenv\MagicQuill\lib\site-packages\transformers\utils\hub.py", line 450, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: 'D:\project\pythonProject\MagicQuill\MagicQuill\../models/llava-v1.5-7b-finetune-clean'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
(MagicQuill) PS D:\project\pythonProject\MagicQuill>

![image](https://github.com/user-attachments/assets/d47fd194-9c47-4b90-8c86-e4a4083be6c7)

**Comment by zliucz** [comment]
Hi, @z-jin-1. I believe this is another incompatibility issue between Linux and Windows.

Try to modify the 25th line in [llava_new.py](https://github.com/magic-quill/MagicQuill/blob/main/MagicQuill/llava_new.py) from `model_path = os.path.join(current_dir, "../models/llava-v1.5-7b-finetune-clean")` to `model_path = os.path.normpath(os.path.join(current_dir, "..", "models", "llava-v1.5-7b-finetune-clean"))`. I hope this helps.

Meanwhile, we'll try our best to update our system to be compatible with both Linux and Windows.

**Comment by z-jin-1** [comment]
@zliucz

**Comment by z-jin-1** [comment]
aaa

**Comment by z-jin-1** [comment]
@zliucz 
Thank you very much for your reply. Your timely response has been very helpful to me. I was able to solve the problem I was facing using the method you provided. While working on the next steps, I also discovered some other issues and made some appropriate modifications:
     1. On line 113 of the brushnet_nodes.py file, the parameter "force_hooks=False" needs to be commented out as it is an unexpected argument.
     2. On line 13 of the folder_paths.py file, the path '../models' needs to be changed to the local model download location, preferably an absolute path.
     3. In the MagicQuill.py file, the class MagicQuill needs to override the example_inputs method in the parent class, but I don't know what needs to be overridden, so I just made a regular output.
`class MagicQuill(FormComponent):
    def __init__(
        self,
        value: str | Callable | None = None,
        *,
        theme: str | None = None,
        url: str | None = None,
        visible: bool = True,
        render: bool = True,
    ):
        self.theme = theme
        self.url = url
        super().__init__(
            value=value,
            render=render,
        )

    def preprocess(self, payload: str | None) -> str | None:
        """
        Parameters:
            payload: the text entered in the textarea.
        Returns:
            Passes text value as a {str} into the function.
        """
        # print("preprocess", payload)
        return None if payload is None else payload

    def postprocess(self, value: str | None) -> str | None:
        """
        Parameters:
            value: Expects a {str} returned from function and sets textarea value to it.
        Returns:
            The value to display in the textarea.
        """
        # print("postprocess", value)
        return None if value is None else value

    def api_info(self) -> dict[str, Any]:
        return {"type": "string"}

    def example_payload(self) -> Any:
        return "Hello!!"

    def example_value(self) -> Any:
        return "Hello!!"

    def example_inputs(self)-> Any:
        # 实现 example_inputs 方法
        return "Example inputs"`
After the above modifications, the entire system is now functioning properly.

**Comment by zliucz** [comment]
Hi, @z-jin-1. Maybe you can create a new issue page about the new bug. It will be more convenient for later update. We’ll check the bug asap.

**Comment by z-jin-1** [comment]
> Hi, @z-jin-1. Maybe you can create a new issue page about the new bug. It will be more convenient for later update. We’ll check the bug asap.
Of course. Thank you very much

**Comment by somenewaccountthen** [comment]
I just pulled in linux. And get this same error.
Doubt was completed.

**Comment by somenewaccountthen** [comment]
> python gradio_run.py
Traceback (most recent call last):
  File "/my_dev/big_ai_etc/imaging/magicquill/gradio_run.py", line 16, in <module>
    from MagicQuill.llava_new import LLaVAModel
  File "/my_dev/big_ai_etc/imaging/magicquill/MagicQuill/llava_new.py", line 10, in <module>
    from llava.conversation import conv_templates, SeparatorStyle
ModuleNotFoundError: No module named 'llava'

**Comment by zliucz** [comment]
@somenewaccountthen Please show me your installation log of of llava1.2.2.post1 to see what's wrong.

'''
cp -f pyproject.toml MagicQuill/LLaVA/
pip install -e MagicQuill/LLaVA/
'''

**Comment by somenewaccountthen** [comment]
> @somenewaccountthen Please show me your installation log of of llava1.2.2.post1 to see what's wrong.
> 
> ''' cp -f pyproject.toml MagicQuill/LLaVA/ pip install -e MagicQuill/LLaVA/ '''

I updated my comment. I did indeed copy paste the project URL from the browser and installed without recursive.
