### ISSUE TITLE
why SD 1.5 and not SDXL?

### ISSUE THREAD

**Issue by blacklig** [magic-quill/MagicQuill#2]
HI guys, nice work, but why did you chose SD1.5?

Also why no inpainting models but just normal checkpoints?

**Comment by zliucz** [comment]
Thanks for your questions!

Actually, we do have a dedicated inpainting module! We employed BrushNet (https://github.com/TencentARC/BrushNet) as an inpainting branch. You can find our inpainting checkpoints at https://huggingface.co/LiuZichen/MagicQuill-models/tree/main/inpaint. The inpainting branch is a versatile plugin that enhances the editing capabilities of SD1.5. We're seeing good performance metrics with this implementation. 

We chose SD1.5 with 512 resolution after careful consideration of the performance-cost tradeoff. SD1.5 requires less VRAM, has a faster inference time, and is more accessible for users with consumer-grade GPUs.

**Comment by Hunt3rseeker** [comment]
@zliucz First of all I just want to say; this looks like a very fun and promising project. I'm excited to try it out!
It makes sense to first focus on people with consumer-grade GPUs. Are there any plans to add other types of checkpoints?

**Comment by Hunt3rseeker** [comment]
> Thanks for your questions!
> 
> Actually, we do have a dedicated inpainting module! We employed BrushNet (https://github.com/TencentARC/BrushNet) as an inpainting branch. You can find our inpainting checkpoints at https://huggingface.co/LiuZichen/MagicQuill-models/tree/main/inpaint. The inpainting branch is a versatile plugin that enhances the editing capabilities of SD1.5. We're seeing good performance metrics with this implementation.
> 
> We chose SD1.5 with 512 resolution after careful consideration of the performance-cost tradeoff. SD1.5 requires less VRAM, has a faster inference time, and is more accessible for users with consumer-grade GPUs.

By the way, I think there's something wrong with these lines

**install llava environment**

cp -f pyproject.toml MagicQuill/LLaVA/

I guess it should be cd, not cp, but even if I change that, it cannot find the specific file.

**Comment by zliucz** [comment]
Hi, there @Hunt3rseeker. You should clone this repo with "--recursive" because we use LLaVA (https://github.com/haotian-liu/LLaVA) as a git submodule at path MagicQuill/LLaVA/. Otherwise, you will find MagicQuill/LLaVA/ missing. 

Once you get LLaVA submodule ready, run the command: "cp -f pyproject.toml MagicQuill/LLaVA/" and install LLaVA related packages :). 

As for the future plan, our top priority right now is preparing the ComfyUI custom nodes for MagicQuill. This will make our editing system more accessible and easier to integrate into existing workflows. Please star ⭐ our repo to stay tuned for the upcoming release!

**Comment by magekinnarus** [comment]
> As for the future plan, our top priority right now is preparing the ComfyUI custom nodes for MagicQuill. This will make our editing system more accessible and easier to integrate into existing workflows. Please star ⭐ our repo to stay tuned for the upcoming release!

I think this is a really fantastic tool. Having said that, I think making a one-step installer for Windows or making your tool compatible with Mac should take priority over creating a Comfy node pack. I understand that making Comfy nodes is a low-hanging fruit but you should consider the SD user distribution. I find it difficult to believe that most Comfy users will use SD 1.5 no matter how good the tool is. In other words, Comfy user base is not your target audience. And to be honest, the vast majority of your potential users will find the CLI-based installation process daunting. So, you should prioritize making it as easy as possible for people to install and use your tool. Just my 2 cents.

**Comment by blacklig** [comment]
> Thanks for your questions!
> 
> Actually, we do have a dedicated inpainting module! We employed BrushNet (https://github.com/TencentARC/BrushNet) as an inpainting branch. You can find our inpainting checkpoints at https://huggingface.co/LiuZichen/MagicQuill-models/tree/main/inpaint. The inpainting branch is a versatile plugin that enhances the editing capabilities of SD1.5. We're seeing good performance metrics with this implementation.
> 
> We chose SD1.5 with 512 resolution after careful consideration of the performance-cost tradeoff. SD1.5 requires less VRAM, has a faster inference time, and is more accessible for users with consumer-grade GPUs.

Hi, thanks for taking time to reply me.

So only hardware performance was the main part to chose SD1.5? Or do you consider still SD1.5 inpainting models superior over SDXL? Me myself still cannot decide which one is better.. for sure SD 1.5 still has lot of to say I think in some areas like inpainting and control nets etc
