### ISSUE TITLE
有comfyui版本的吗

### ISSUE THREAD

**Issue by chenpipi0807** [magic-quill/MagicQuill#21]
有comfyui版本的吗

**Comment by zliucz** [comment]
Yes. We do have a [ComfyUI custom node](https://github.com/magic-quill/MagicQuill/blob/main/docs/comfyui.png). Currently, we are trying our best working on it to make it ready for release.

**Comment by chenpipi0807** [comment]
我看你们似乎只做了1.5版本的模型，是否会支持xl，flux以及SD3.5呢
