### ISSUE TITLE
Image save

### ISSUE THREAD

**Issue by SparklyBird** [magic-quill/MagicQuill#26]
How do I save the images? I tried just using "Save image as...":
![image](https://github.com/user-attachments/assets/f5afc52b-7248-410a-a4c4-d8933502ecfb)
 
But that just saves black image:
![image](https://github.com/user-attachments/assets/96120f03-6b47-4e49-8434-c2ccdaeb25c4)

Also tried just copying and putting it in like draw.io or just Microsoft Word file, but it appeared just as blank white image.

Edit:
Noticed that it only happens when try to save image that is in the editing part not the output

**Comment by zliucz** [comment]
Hi, we updated a save button for images on the editing area. Check our latest code :)

**Comment by SparklyBird** [comment]
> Hi, we updated a save button for images on the editing area. Check our latest code :)

Tried it and I think it doesnt work. When press button nothing happens. Does it saves image that is like in the upload image field or in the field after changes are generated?

**Comment by zliucz** [comment]
> > Hi, we updated a save button for images on the editing area. Check our latest code :)
> 
> Tried it and I think it doesnt work. When press button nothing happens. Does it saves image that is like in the upload image field or in the field after changes are generated?

@SparklyBird Hi. The default save path is at the ./output folder. Would you please check it? Thanks. :)

**Comment by SparklyBird** [comment]
> Quote reply
> Reference

Yup images there, tnx )
