### ISSUE TITLE
Right Click - Save As... = Blank 8KB .PNG

### ISSUE THREAD

**Issue by TacImpulse** [magic-quill/MagicQuill#27]
Got MagicQuill rollin' on Win 11 with a little work. But, when I go to save an image with Right Click - Save As... It just saves a completely blank 8kb .png file. Any ideas? Thanks y'all!

**Comment by zliucz** [comment]
Hi, this is a known bug. Saving image by right-clicking the left part of the canvas will give you an empty image. We are currently working on it. 

Try to save your image by right-clicking the right part of the canvas. 
![sample](https://github.com/user-attachments/assets/277bd67d-957b-4c81-a1f6-8c683566bea7)
