### ISSUE TITLE
Getting Error after new Installation

### ISSUE THREAD

**Issue by chnisar515** [magic-quill/MagicQuill#34]
when i try to run this command

> $env:CUDA_VISIBLE_DEVICES=0; python gradio_run.py

then i got this error:

> The filename, directory name, or volume label syntax is incorrect.

i already replaced the line 57 of file `brushnet_nodes.py` with `brushnet = brushnet.replace('/','\\')`

**Comment by edtse** [comment]
if you are using the $env command, you should be running in Powershell.  If you are running under the regular command prompt, you can run like 

set CUDA_VISIBLE_DEVICES=0
python gradio_run.py

**Comment by chnisar515** [comment]
> if you are using the $env command, you should be running in Powershell. If you are running under the regular command prompt, you can run like
> 
> set CUDA_VISIBLE_DEVICES=0 python gradio_run.py

first of all Thank you so much for reply. i followed your steps and when i use `set CUDA_VISIBLE_DEVICES=0` it successfully set it and after when i use this command `python gradio_run.py` i am getting error which is below.

> (MagicQuill) E:\My AI\MagicQuill\MagicQuill>set CUDA_VISIBLE_DEVICES=0
(MagicQuill) E:\My AI\MagicQuill\MagicQuill>python gradio_run.py
Traceback (most recent call last):
  File "E:\My AI\MagicQuill\MagicQuill\gradio_run.py", line 17, in <module>
    from MagicQuill.scribble_color_edit import ScribbleColorEditModel
  File "E:\My AI\MagicQuill\MagicQuill\MagicQuill\scribble_color_edit.py", line 9, in <module>
    from .brushnet_nodes import BrushNetLoader, BrushNet, BlendInpaint, get_files_with_extension
  File "E:\My AI\MagicQuill\MagicQuill\MagicQuill\brushnet_nodes.py", line 58
        brushnet_file = os.path.join(self.inpaint_files[brushnet], brushnet)
    ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by chnisar515** [comment]
i am getting this error now

(MagicQuill) E:\My AI\MagicQuill\MagicQuill>set CUDA_VISIBLE_DEVICES=0 && python gradio_run.py
Traceback (most recent call last):
  File "E:\My AI\MagicQuill\MagicQuill\gradio_run.py", line 17, in <module>
    from MagicQuill.scribble_color_edit import ScribbleColorEditModel
  File "E:\My AI\MagicQuill\MagicQuill\MagicQuill\scribble_color_edit.py", line 9, in <module>
    from .brushnet_nodes import BrushNetLoader, BrushNet, BlendInpaint, get_files_with_extension
  File "E:\My AI\MagicQuill\MagicQuill\MagicQuill\brushnet_nodes.py", line 58
            brushnet_file = os.path.join(self.inpaint_files[brushnet], brushnet)
    ^
TabError: inconsistent use of tabs and spaces in indentation

So can someone help?

**Comment by edtse** [comment]
You have to follow the windows guide here
https://github.com/magic-quill/MagicQuill/issues/11

but basically, you have to 

open brushnet_nodes.py with editor (MagicQuill\MagicQuill\brushnet_nodes.py)
replace this line:
brushnet_file = os.path.join(self.inpaint_files[brushnet], brushnet)
with:
brushnet = brushnet.replace('/', '\\')
brushnet_file = os.path.join(self.inpaint_files[brushnet], brushnet)

**Comment by chnisar515** [comment]
> set CUDA_VISIBLE_DEVICES=0 python gradio_run.py

its fixed. thank you.

**Comment by zliucz** [comment]
Hi, we’ve updated code to fix path bug in Windows. Please pull the latest code.
