### ISSUE TITLE
SAVE Option And Image Size

### ISSUE THREAD

**Issue by PixelArmony** [magic-quill/MagicQuill#36]
Hello,

Why isn’t there an option to save the image? Also, why does the loaded image always have the same size instead of using its original size or properties? I find this really bizarre. Can you please fix these issues? Thank you!

**Comment by zliucz** [comment]
Hi, there. We have added a save button to save the image in the editing area. Thanks [lior777](https://github.com/lior007). Please pull the latest code.

Meanwhile, we automatically resize the shortest edge to 512 pixels to save the memory and optimize the performance. You may change `load_and_resize_image` functions in the [gradio_run.py](https://github.com/magic-quill/MagicQuill/blob/main/gradio_run.py).

**Comment by PixelArmony** [comment]
Oh, OK! Than you!
You guys did a really good job, I enjoy your tool very much!

**Comment by zliucz** [comment]
Consider give us a star if you like our job :). Thanks for your kind words.

**Comment by PixelArmony** [comment]
I've updated the value from 512 to 1024. It's naturally a bit slower, but it works good too. Thanks for the tip!
I appreciate it! (I've also followed you and added a star.)

```
def load_and_resize_image(base64_image, convert_to='RGB', max_size=1024):
    """Load and preprocess a base64 image, resize if necessary."""
    image = read_base64_image(base64_image)
    image = image.convert(convert_to)
    width, height = image.size
    scaling_factor = max_size / min(width, height)
    new_size = (int(width * scaling_factor), int(height * scaling_factor))
    image = image.resize(new_size, Image.LANCZOS)
    image_array = np.array(image).astype(np.float32) / 255.0
    image_tensor = torch.from_numpy(image_array)[None,]
    return image_tensor
```
