### ISSUE TITLE
'res' error

### ISSUE THREAD

**Issue by xu2k** [magic-quill/MagicQuill#37]
I ran the Gradio demo, but it isn't working and shows an error saying 'res

**Comment by yvz38** [comment]
me, too. This is what I get:

![Screenshot 2024-11-21 at 06-26-12 Gradio](https://github.com/user-attachments/assets/6b0b3fae-7a5e-425c-84bd-3998bf5aa783)


![Screenshot 2024-11-21 061711](https://github.com/user-attachments/assets/371d3d07-8cc3-49da-9b1f-d35d052a49fc)

**Comment by Jandown** [comment]
> me, too. This is what I get:
> 
> ![Screenshot 2024-11-21 at 06-26-12 Gradio](https://private-user-images.githubusercontent.com/22767528/388366783-6b0b3fae-7a5e-425c-84bd-3998bf5aa783.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNzA4MDAsIm5iZiI6MTczMjE3MDUwMCwicGF0aCI6Ii8yMjc2NzUyOC8zODgzNjY3ODMtNmIwYjNmYWUtN2E1ZS00MjVjLTg0YmQtMzk5OGJmNWFhNzgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDA2MjgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMjNhODY3ZDA1YjU4N2FkMDkyYmQwZGI5OTQyYjg2NjQ4NTlhMmM0OTY5MDM5ZjEyZmY3OWExZTc3ZTc1MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7XRxE2inWD-mPtxgXUZsVsnhEF2UZ3Ge3nOfZMWT01Q)
> 
> ![Screenshot 2024-11-21 061711](https://private-user-images.githubusercontent.com/22767528/388366583-371d3d07-8cc3-49da-9b1f-d35d052a49fc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNzA4MDAsIm5iZiI6MTczMjE3MDUwMCwicGF0aCI6Ii8yMjc2NzUyOC8zODgzNjY1ODMtMzcxZDNkMDctOGNjMy00OWRhLTliMWYtZDM1ZDA1MmE0OWZjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDA2MjgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4ZTNiM2Q5MmJmMzM5OTk3NGVlYWNhODZiZjg2ZWNjMWY3MjVhYjAwZDJlNjM2YmYyNTc4NjhiMDI2YjlhOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bGU0WlY8SMVnYH1aHA37bQc9qWxaQjAuZKhZfOa-PCg)

the same problem

**Comment by zliucz** [comment]
Hi, there. Multiple reasons could cause this error. I have updated the code to print more detailed error report. Please pull the latest code and check the error again.

**Comment by yvz38** [comment]
Hi, thanks for the update. The installer for windows is indeed very nice. I've made a fresh pull and install, and now I see this when I klick run:

![Screenshot 2024-11-22 at 01-16-47 Gradio](https://github.com/user-attachments/assets/73198bf3-4951-4082-bcfc-82ca5d628225)

![Screenshot 2024-11-22 011758](https://github.com/user-attachments/assets/ff9c6bae-6f06-4291-954d-ea9beac06e93)

**Comment by zliucz** [comment]
I haven't met this error before. I think it suggests something wrong with your xformers package.

But I'm more than curious why such errors occur because I think none of the steps have installed xformers. Did you install it before?

 Maybe try to re-install it by following the [link](https://github.com/facebookresearch/xformers).
