### ISSUE TITLE
Step 4 error

### ISSUE THREAD

**Issue by mrlungile** [magic-quill/MagicQuill#39]
This is the error I'm getting when I'm on Step 4. Help please

(MagicQuill) andre@MacBook-Air ~ % pip install gradio_magicquill-0.0.1-py3-none-any.whl
WARNING: Requirement 'gradio_magicquill-0.0.1-py3-none-any.whl' looks like a filename, but the file does not exist
Processing ./gradio_magicquill-0.0.1-py3-none-any.whl
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/Users/andre/gradio_magicquill-0.0.1-py3-none-any.whl'

**Comment by bruceyyu** [comment]
@mrlungile I think it's because you are running at the directory ~, not the directory where you cloned MagicQuill
