### ISSUE TITLE
How to set `load_in_8bit_fp32_cpu_offload=True` and pass a custom `device_map` to `from_pretrained` in MagicQuill?

### ISSUE THREAD

**Issue by programandoxx** [magic-quill/MagicQuill#40]
When I try to run in a Windows, appears this:

" File "C:\miniconda3\envs\MagicQuill\lib\site-packages\transformers\modeling_utils.py", line 3790, in from_pretrained
    raise ValueError(
ValueError:
                        Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit
                        the quantized model. If you want to dispatch the model on the CPU or the disk while keeping
                        these modules in 32-bit, you need to set `load_in_8bit_fp32_cpu_offload=True` and pass a custom
                        `device_map` to `from_pretrained`. Check
                        https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu
                        for more details.   "

Someone can tell me how to set `load_in_8bit_fp32_cpu_offload=True` and pass a custom `device_map` to `from_pretrained` on the code of MagicQuill?

I don't understand programming (and it contribute to me don't understanding the suggested documentation in the link), I'm trying to follow the MagicQuill tutorial and what you commented on 'Issues' and I have the impression that I'm almost finally able to run the program, with just this last part left to solve. I would be immensely grateful to anyone who can help me.

**Comment by asifraja** [comment]
@programandoxx , I know the feeling as I am also new to python and running models locally but I have managed to run it on my local laptop by setting **cuda** to **cpu** on the following file. In MagicQuill\LLaVA\llava\model\builder.py file at line 26 for the parameter **device** is set to **cpu** from its default value of **cuda**. After that I was able to ran it fine. 

![image](https://github.com/user-attachments/assets/500175ea-7712-4aac-a65d-78014c5beff4)
