### ISSUE TITLE
Brush mask should be a solid color, not a dashed pattern. Very hard to accurately brush edges. An opacity slider for the brush would be nice too.

### ISSUE THREAD

**Issue by jakiei** [magic-quill/MagicQuill#41]
Feature Request:

Allow us to use solid colors for drawing with the brush masks (let us customize the color with a color pick tool). There should be an opacity slider to see the transparency through the masked regions. Basically, just mimic Photoshop.

The current dashed pattern is very distracting, hard to identify edges, and unprofessional (from a creators point of view). It requires twice the amount of time for me to make a mask because I need to double check that the mask is actually painted over a specific region of an image.

**Comment by zliucz** [comment]
Would be great if you open up a pull request to implement these features :). Thanks.
