### ISSUE TITLE
Full Model Zip

### ISSUE THREAD

**Issue by tpcdaz** [magic-quill/MagicQuill#44]
Is it possible for you to supply an alternative link for the full 22gb model zip?  I've tried multiple times and the download keeps failing mid way. It happens via python as well as if I try to download the zip manually via the browser. Thank you.

**Comment by zliucz** [comment]
HI, try to download from [Huggingface](https://huggingface.co/LiuZichen/MagicQuill-models). :)

**Comment by tpcdaz** [comment]
ah ..thank you I didn't know you could do that. Appreciate it :)

**Comment by x4080** [comment]
@zliucz what folder to clone huggingface checkpoints ? Is it MagicQuill folder ? or models ? Dont have a clue in https://huggingface.co/spaces/AI4Editing/MagicQuill/tree/main/MagicQuill files
