### ISSUE TITLE
Cant open gradio_run.py

### ISSUE THREAD

**Issue by ken456789** [magic-quill/MagicQuill#45]
![Screenshot_1](https://github.com/user-attachments/assets/0b115b1c-8647-47b6-90c5-e20fe3dd56cc)

![Screenshot_2](https://github.com/user-attachments/assets/20a3aa17-86b2-422e-9a79-ce26a05f1cf9)

Cant open because the problem above, i had downloaded all the model File, Please how to solve,

Thank you.

**Comment by ken456789** [comment]
![Screenshot_2](https://github.com/user-attachments/assets/2a8ac0c4-fccd-42c1-9783-2ab74601f225)

**Comment by BlaiseRodrigues** [comment]
Did you install the requirements? 

`pip install gradio_magicquill-0.0.1-py3-none-any.whl`

`pip install -r requirements.txt`

**Comment by ken456789** [comment]
after i install this

pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu118

success run gradio_run.

thanks.
