### ISSUE TITLE
on windows error

### ISSUE THREAD

**Issue by z-jin-1** [magic-quill/MagicQuill#48]
windows_setup.bat after clicking the file window flash away, and there is no other effect, where is incompatible? Also between the old windows installation tutorial still useful? Do I still need to create a new folder for model download? Does the substitution assignment code from the old tutorial still require action

**Comment by zliucz** [comment]
- Try to enter `windows_setup.bat` in your Python shell.
- The old Windows installation tutorial is still useful
- Of course, you shall place the checkpoints at ./models
- You don't need to replace any lines in the code now.

**Comment by z-jin-1** [comment]
> * Try to enter `windows_setup.bat` in your Python shell.
> * The old Windows installation tutorial is still useful
> * Of course, you shall place the checkpoints at ./models
> * You don't need to replace any lines in the code now.

Thank you very much for your assistance. I successfully got the latest code running on Windows, and the new installation steps are clear and straightforward. It was easy to follow the steps and get it running, and it's also very convenient to use. Thanks for your help! I have a small suggestion: could you enhance the save functionality in the future? For example, allowing users to choose the save path or name would be great. Initially, I thought the save button was not working because there was no prompt after clicking it. Later, I discovered that it automatically saves to the "output" folder without any indication on the page. I hope you have a wonderful day!

**Comment by zliucz** [comment]
Glad to hear that you finally made it running :). Thanks for your suggestion.

**Comment by zliucz** [comment]
I pin this issue in case there will be any users who encounter similar issues.
