### ISSUE TITLE
Windows command line guidance issue

### ISSUE THREAD

**Issue by irowbin** [magic-quill/MagicQuill#49]
It took me a while to run the command `copy /Y pyproject.toml MagicQuill\LLaVA` on Windows because I was using PowerShell. The documentation did not specify which interface to use for executing the command line. As a result, I converted the command to the PowerShell format: `Copy-Item -Path pyproject.toml -Destination "MagicQuill\LLaVA" -Force`, and it ran successfully.

If anyone is confused while trying to execute the command line as a PowerShell user, remember to use `Copy-Item -Path pyproject.toml -Destination "MagicQuill\LLaVA" -Force`.

Thank you!

**Comment by zliucz** [comment]
Hi! Thanks for your tips. Will update our `README.md` soon.
