### ISSUE TITLE
I would like to know what kind of machine configuration is required for this project to be deployed locally?

### ISSUE THREAD

**Issue by Mingsirdon** [magic-quill/MagicQuill#5]
I deployed this project on my Windows computer, but the running prompt CUDA is low on memory, so I would like to know what kind of machine configuration is needed to run this project locally.

**Comment by zliucz** [comment]
Hi. We just updated the readme about the hardware requirements.

- Instant prompt guessing ("Draw&Guess") requires ~5GB VRAM
- Image editing operations require ~15GB VRAM

Normally, I suggest running our project on a 24GB VRAM GPU. For users with limited GPU resources, please try our [Huggingface Demo](https://huggingface.co/spaces/AI4Editing/MagicQuill) or [Web Demo (Alipay Cloud)](http://magic.chenjunfeng.xyz/).

**Comment by Mingsirdon** [comment]
Thanks for the answer
