### ISSUE TITLE
OSError: Error no file named 

### ISSUE THREAD

**Issue by Sami2609** [magic-quill/MagicQuill#50]
Hello, I am encountering this issue: OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory C:\Program Files (x86)\MagicQuill\models\llava-v1.5-7b-finetune-clean.

### **Checklist**

- [ x] I have searched the documentation and FAQs.  
- [ x] I have searched for similar issues but couldn’t find a solution.  
- [x ] I have provided clear and detailed information about the issue.  

---

### **Issue/Feature Request Description**

**Type of Issue:**  
- [ ] Bug  
- [ ] Feature Request  
- [x ] Question  

**Summary**:  
 It did a similar issue for me with llava-v1.5-7b-finetune-clean_config where it told me it couldn't find config.json and it got solved when i renamed  llava-v1.5-7b-finetune-clean_config to config. But in regards to the other files... I don't know what to do... I downloaded the files from [huggingface](https://huggingface.co/LiuZichen/MagicQuill-models/tree/main)

---(MagicQuill) C:\Program Files (x86)\MagicQuill>set CUDA_VISIBLE_DEVICES=0 && python gradio_run.py
Total VRAM 8188 MB, total RAM 32387 MB
pytorch version: 2.1.2+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Laptop GPU : native
Using pytorch cross attention
['C:\\Program Files (x86)\\MagicQuill', 'C:\\Users\\96773\\miniconda3\\envs\\MagicQuill\\python310.zip', 'C:\\Users\\96773\\miniconda3\\envs\\MagicQuill\\DLLs', 'C:\\Users\\96773\\miniconda3\\envs\\MagicQuill\\lib', 'C:\\Users\\96773\\miniconda3\\envs\\MagicQuill', 'C:\\Users\\96773\\miniconda3\\envs\\MagicQuill\\lib\\site-packages', '__editable__.llava-1.2.2.post1.finder.__path_hook__', 'C:\\Program Files (x86)\\MagicQuill\\MagicQuill']
You are using the default legacy behaviour of the <class 'transformers.models.llama.tokenization_llama.LlamaTokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
Traceback (most recent call last):
  File "C:\Program Files (x86)\MagicQuill\gradio_run.py", line 21, in <module>
    llavaModel = LLaVAModel()
  File "C:\Program Files (x86)\MagicQuill\MagicQuill\llava_new.py", line 26, in __init__
    self.tokenizer, self.model, self.image_processor, self.context_len = load_pretrained_model(
  File "C:\Program Files (x86)\MagicQuill\MagicQuill\LLaVA\llava\model\builder.py", line 117, in load_pretrained_model
    model = LlavaLlamaForCausalLM.from_pretrained(
  File "C:\Users\96773\miniconda3\envs\MagicQuill\lib\site-packages\transformers\modeling_utils.py", line 3338, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory C:\Program Files (x86)\MagicQuill\models\llava-v1.5-7b-finetune-clean.

Thanks in advance for any help

**Comment by zliucz** [comment]
Would you please take a screenshot for the folder C:\Program Files (x86)\MagicQuill\models\llava-v1.5-7b-finetune-clean? Let's see what is missing.

**Comment by Sami2609** [comment]
<img width="693" alt="Screenshot 2024-11-22 090215" src="https://github.com/user-attachments/assets/37e07222-3f71-422a-8a24-ceaa7e50d9b5">

**Comment by zliucz** [comment]
![image](https://github.com/user-attachments/assets/f06b9013-47e1-44c9-b07f-bb91bc0baeac)
Seems a bit different from mine. Would you please change the filename accordingly? Thanks.

**Comment by zliucz** [comment]
![image](https://github.com/user-attachments/assets/fbfcddd2-540b-43c0-b167-35f6abdcccf4)

Hi, seems your filenames are a bit different from mine. Would you please change your filename accordingly? Thanks.

**Comment by Sami2609** [comment]
done. now it is downloading pytorch_model.bin for the first time. Thank you very much

**Comment by zliucz** [comment]
Glad to hear that :).
