### ISSUE TITLE
Support drag-and-drop image onto source image box

### ISSUE THREAD

**Issue by tristan88888** [magic-quill/MagicQuill#52]
**PLEASE READ BEFORE SUBMITTING AN ISSUE**  

MagicQuill is not a commercial software but a research project. While we strive to improve and maintain it, support is provided on a best-effort basis. Please be patient and respectful in your communications.
To help us respond faster and better, please ensure the following:  

1. **Search Existing Resources**: Have you looked through the documentation (e.g., hardware requirement and setup steps), and searched online for potential solutions?  
2. **Avoid Duplication**: Check if a similar issue already exists.  

If the issue persists, fill out the details below.

---

### **Checklist**

- [X ] I have searched the documentation and FAQs.  
- [X] I have searched for similar issues but couldn’t find a solution.  
- [X] I have provided clear and detailed information about the issue.  

---

### **Issue/Feature Request Description**

**Type of Issue:**  
- [ ] Bug  
- [X] Feature Request  
- [ ] Question  

**Summary**:  
  

Currently the source image needs to be uploaded through a load file dialog box. Most image workflows support drag-and-drop of images into the source image box. This would make the tool much more user-friendly.
---

### **Steps to Reproduce (For Bugs Only)**  
1.  
2.  
3.  

**Expected Behavior**:  

**Actual Behavior**:  
  

---

### **Additional Context/Details**  

---

### **Environment**  
- **OS**:  
- **Version**:  
- **Any Relevant Dependencies**:  

---

### **Feature Request Specifics (If Applicable)**  
- **What problem does this solve?**:  
- **How will this feature improve the project?**:

User-friendliness would be greatly enhanced.

**Comment by bruceyyu** [comment]
see ad6be2b18b88d446d5891b5f6c9c1bd728a7b610
