### ISSUE TITLE
Running out of memory

### ISSUE THREAD

**Issue by c14210167** [magic-quill/MagicQuill#53]
Hello, I'm trying to run MagicQuill but I don't have that much VRAM. Is there a way for me to still run it? Thanks.

**The logs:**
D:\MagicQuill\MagicQuill>conda activate MagicQuill

(MagicQuill) D:\MagicQuill\MagicQuill>python gradio_run.py
Total VRAM 4096 MB, total RAM 16236 MB
pytorch version: 2.1.2+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1650 : native
Using pytorch cross attention
['D:\\MagicQuill\\MagicQuill', 'D:\\Miniconda\\Miniconda\\envs\\MagicQuill\\python310.zip', 'D:\\Miniconda\\Miniconda\\envs\\MagicQuill\\DLLs', 'D:\\Miniconda\\Miniconda\\envs\\MagicQuill\\lib', 'D:\\Miniconda\\Miniconda\\envs\\MagicQuill', 'D:\\Miniconda\\Miniconda\\envs\\MagicQuill\\lib\\site-packages', '__editable__.llava-1.2.2.post1.finder.__path_hook__', 'D:\\MagicQuill\\MagicQuill\\MagicQuill']
D:\Miniconda\Miniconda\envs\MagicQuill\lib\site-packages\huggingface_hub\file_download.py:797: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
We will use 90% of the memory on device 0 for storing the model, and 10% for the buffer to avoid OOM. You can set `max_memory` in to a higher value to use more memory (at your own risk).
Traceback (most recent call last):
  File "D:\MagicQuill\MagicQuill\gradio_run.py", line 21, in <module>
    llavaModel = LLaVAModel()
  File "D:\MagicQuill\MagicQuill\MagicQuill\llava_new.py", line 26, in __init__
    self.tokenizer, self.model, self.image_processor, self.context_len = load_pretrained_model(
  File "D:\MagicQuill\MagicQuill\MagicQuill\LLaVA\llava\model\builder.py", line 117, in load_pretrained_model
    model = LlavaLlamaForCausalLM.from_pretrained(
  File "D:\Miniconda\Miniconda\envs\MagicQuill\lib\site-packages\transformers\modeling_utils.py", line 3790, in from_pretrained
    raise ValueError(
ValueError:
                        Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit
                        the quantized model. If you want to dispatch the model on the CPU or the disk while keeping
                        these modules in 32-bit, you need to set `load_in_8bit_fp32_cpu_offload=True` and pass a custom
                        `device_map` to `from_pretrained`. Check
                        https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu
                        for more details.

**Comment by zliucz** [comment]
Hi. Unfortunately, only GPU with at least 8GB VRAM can run MagicQuill :(.

You may try to duplicate our [Huggingface demo](https://huggingface.co/spaces/AI4Editing/MagicQuill) if you are interested.
