### ISSUE TITLE
Question : ImportError: cannot import name 'SAC_IGNORED_OPS' from 'torch.utils.checkpoint' (/opt/conda/lib/python3.10/site-packages/torch/utils/checkpoint.py)

### ISSUE THREAD

**Issue by x4080** [magic-quill/MagicQuill#56]
I got this error after following the installed instruction, anybody knows why ?

Thanks

**Comment by tristan88888** [comment]
I didn't encounter this. I think it's related to your torch version. I'm using 2.3.0+cu118 and it works fine.

**Comment by x4080** [comment]
@tristan88888 I'll try your suggestion, thanks

**Comment by x4080** [comment]
The strange thing is this only happens on kaggle, like just open new notebook in kaggle (using cpu)
and run
```
from torch.utils.checkpoint import SAC_IGNORED_OPS as _ignored_ops  # type: ignore
```

and it will show errors, using newer or older torch dont make any changes, dont know what happened, close it for now
