### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by buddylee7** [magic-quill/MagicQuill#58]
Getting the following error when trying to run:

OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory D:\MagicQuill\models\llava-v1.5-7b-finetune-clean.

**Comment by zliucz** [comment]
Hi, would you please take a screenshot of your folder at path C:\GenAI\MagicQuill\models\llava-v1.5-7b-finetune-clean?
