### ISSUE TITLE
Comfyui ?

### ISSUE THREAD

**Issue by kuronico59** [magic-quill/MagicQuill#59]
Hi i can see you have post comfyui node, but I dont see it in manager, how to install it please ?
nice nice work !!

**Comment by bruceyyu** [comment]
coming soon. This or next week!

**Comment by bruceyyu** [comment]
@kuronico59 check it out here https://github.com/magic-quill/MagicQuill/tree/comfyui

**Comment by zliucz** [comment]
Hi, there! The MagicQuill ComfyUI node has been released! Check this out https://github.com/magic-quill/ComfyUI_MagicQuill 🔥🔥🔥
