### ISSUE TITLE
No module named 'llava'

### ISSUE THREAD

**Issue by udanawimukthi** [magic-quill/MagicQuill#60]
after run python gradio_run.py:

Traceback (most recent call last):
  File "F:\MagicQuill\gradio_run.py", line 16, in <module>
    from MagicQuill.llava_new import LLaVAModel
  File "F:\MagicQuill\MagicQuill\llava_new.py", line 10, in <module>
    from llava.conversation import conv_templates, SeparatorStyle
ModuleNotFoundError: No module named 'llava'

**Comment by bruceyyu** [comment]
pls check docs https://github.com/magic-quill/MagicQuill?tab=readme-ov-file#setup

**Comment by getpool** [comment]
I also installed it according to the above steps, and it also prompted this 
ModuleNotFoundError: No module named 'llava'

**Comment by narfel** [comment]
This error is a result from either following https://github.com/magic-quill/MagicQuill?tab=readme-ov-file#setup or running the windows_setup.bat. Specifically this portion:
:: Install the llava environment
echo Setting up LLaVA environment...
if not exist MagicQuill\LLaVA (
echo Directory MagicQuill\LLaVA does not exist. Ensure the folder structure is correct.
exit /b 1
)
copy /y pyproject.toml MagicQuill\LLaVA
pip install -e MagicQuill\LLaVA\

For what its worth the resulting directory structure is:
\MagicQuill\MagicQuill\LLaVA\ <- this is where the toml file and llava.egg-info ends up
\MagicQuill\MagicQuill\ <- this is where llava_new.py ends up and cannot do "import llava"
