### ISSUE TITLE
error on last step on windows installation

### ISSUE THREAD

**Issue by mcachy23** [magic-quill/MagicQuill#61]
![Screenshot 2024-11-25 194226](https://github.com/user-attachments/assets/2e67c763-cb77-4869-9e24-9f126a671a76)
**PLEASE READ BEFORE SUBMITTING AN ISSUE**  

MagicQuill is not a commercial software but a research project. While we strive to improve and maintain it, support is provided on a best-effort basis. Please be patient and respectful in your communications.
To help us respond faster and better, please ensure the following:  

1. **Search Existing Resources**: Have you looked through the documentation (e.g., hardware requirement and setup steps), and searched online for potential solutions?  
2. **Avoid Duplication**: Check if a similar issue already exists.  

If the issue persists, fill out the details below.

---

### **Checklist**

- [ ] I have searched the documentation and FAQs.  
- [x] I have searched for similar issues but couldn’t find a solution.  
- [ ] I have provided clear and detailed information about the issue.  

---

### **Issue/Feature Request Description**

**Type of Issue:**  
- [ ] Bug  
- [ ] Feature Request  
- [ ] Question  

**Summary**:  
  

---

### **Steps to Reproduce (For Bugs Only)**  
1.  
2.  
3.  

**Expected Behavior**:  

**Actual Behavior**:  
  

---

### **Additional Context/Details**  

---

### **Environment**  
- **OS**:  
- **Version**:  
- **Any Relevant Dependencies**:  

---

### **Feature Request Specifics (If Applicable)**  
- **What problem does this solve?**:  
- **How will this feature improve the project?**:

**Comment by mcachy23** [comment]
running windows 
i am on the last step of the install process but cant figure out how to fix

**Comment by IntellectzProductions** [comment]
I did everything that was in the instructions. Downloaded the models. did all requirements, it seems to be still looking for things on hugging face even though I downloaded all 27 gigs of the models and configs.

**Comment by TiegoCampos** [comment]
Same issue here. I made all the process with CMD because Powershell bugs when install torch... and in the PowerShell I can't even activate MagicQuill environment.

**Comment by rzgarespo** [comment]
> Same issue here. I made all the process with CMD because Powershell bugs when install torch... and in the PowerShell I can't even activate MagicQuill environment.

watch this -> youtube.com/watch?v=UE6O6VDPDa8

**Comment by TiegoCampos** [comment]
Thanks @rzgarespo! I just fix this in a minute ago. In my case, for some reason I had changed the name of the models folder. Another thing is that I downloaded and extracted the models manually, so the path to the models itself was subtly wrong. @mcachy23 check if your models corresponds to the path that the error shows.
