### ISSUE TITLE
ModuleNotFoundError: No module named 'llava'

### ISSUE THREAD

**Issue by Amark-cheey** [magic-quill/MagicQuill#69]
(MagicQuill) hujh@a800:~/expriement/1-imageedit/MagicQuill-main$ python gradio_run.py
Traceback (most recent call last):
  File "/home/hujh/expriement/1-imageedit/MagicQuill-main/gradio_run.py", line 16, in <module>
    from MagicQuill.llava_new import LLaVAModel
  File "/home/hujh/expriement/1-imageedit/MagicQuill-main/MagicQuill/llava_new.py", line 10, in <module>
    from llava.conversation import conv_templates, SeparatorStyle
ModuleNotFoundError: No module named 'llava'

**Comment by Amark-cheey** [comment]
![image](https://github.com/user-attachments/assets/76170cfb-Building wheels for collected packages: llava
  Building editable for llava (pyproject.toml) ... done
  Created wheel for llava: filename=llava-1.2.2.post1-0.editable-py3-none-any.whl size=3153 sha256=08b840cbd91e6c6783d01ad029fc28fd3a57929e247f71acc264e112141bb220
  Stored in directory: /tmp/pip-ephem-wheel-cache-ip6e454_/wheels/fa/f8/bd/bdd1880f2c58c5acf6da5a193df9d5999c2ad3b967950681f1
Successfully built llava
Installing collected packages: llava
  Attempting uninstall: llava
    Found existing installation: llava 1.2.2.post1
    Uninstalling llava-1.2.2.post1:
      Successfully uninstalled llava-1.2.2.post1
Successfully installed llava-1.2.2.post1
(MagicQuill) hujh@a800:~/expriement/1-imageedit/MagicQuill-main$ python gradio_run.py
Traceback (most recent call last):
  File "/home/hujh/expriement/1-imageedit/MagicQuill-main/gradio_run.py", line 16, in <module>
    from MagicQuill.llava_new import LLaVAModel
  File "/home/hujh/expriement/1-imageedit/MagicQuill-main/MagicQuill/llava_new.py", line 10, in <module>
    from llava.conversation import conv_templates, SeparatorStyle
ModuleNotFoundError: No module named 'llava'
c459-44a4-a8ac-cac7215d67bf)

**Comment by Amark-cheey** [comment]
Traceback (most recent call last):
  File "/home/hujh/expriement/1-imageedit/MagicQuill-tt/gradio_run.py", line 21, in <module>
    llavaModel = LLaVAModel()
  File "/home/hujh/expriement/1-imageedit/MagicQuill-tt/MagicQuill/llava_new.py", line 26, in __init__
    self.tokenizer, self.model, self.image_processor, self.context_len = load_pretrained_model(
  File "/home/hujh/expriement/1-imageedit/MagicQuill-tt/MagicQuill/LLaVA/llava/model/builder.py", line 117, in load_pretrained_model
    model = LlavaLlamaForCausalLM.from_pretrained(
  File "/home/hujh/anaconda3/envs/llava/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3790, in from_pretrained
    raise ValueError(
ValueError: 
                        Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit
                        the quantized model. If you want to dispatch the model on the CPU or the disk while keeping
                        these modules in 32-bit, you need to set `load_in_8bit_fp32_cpu_offload=True` and pass a custom
                        `device_map` to `from_pretrained`. Check
                        https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu
                        for more details.

**Comment by Amark-cheey** [comment]
CUDA_VISIBLE_DEVICES=0  python gradio_run.py 
use this

**Comment by rzgarespo** [comment]
Windows 11 No module named 'llava'

start the PowerShell and 'cd /to/MagicQuill/MagicQuill/'
2) git clone https://github.com/haotian-liu/LLaVA or just download and unzip the files inside /LLaVA directory
3) copy & paste the "pyproject.toml" form main directory and overwrite the existing one in LLaVA
##Activate the python virtual environemt and  'cd /to/MagicQuill/'
4) pip install torch==2.1.2 torchvision==0.16.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu118
5) pip install gradio_magicquill-0.0.1-py3-none-any.whl
6) pip install -e MagicQuill/LLaVA/
7) pip install -r requirements.txt
8) python gradio_run.py
