### ISSUE TITLE
ModuleNotFoundError: No module named 'gradio_magicquill'

### ISSUE THREAD

**Issue by denisaguirra** [magic-quill/MagicQuill#71]
at last (8. run magicquill)  when a type python gradio_run.py i get this error:

(MagicQuill) C:\MagicQuil\MagicQuill>python gradio_run.py
Traceback (most recent call last):
  File "C:\MagicQuil\MagicQuill\gradio_run.py", line 5, in <module>
    from gradio_magicquill import MagicQuill
ModuleNotFoundError: No module named 'gradio_magicquill'

**Comment by zliucz** [comment]
Hi there, try to re-install gradio_magicquill UI by running
```
pip install gradio_magicquill-0.0.1-py3-none-any.whl
```

Thanks.

**Comment by denisaguirra** [comment]
Thank you very much Zucz, with your help I was able to advance in the installation, but after downloading the processors I had the following error. Do you have any idea how to solve it?

preprocessor_config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 316/316 [00:00<?, ?B/s]
pytorch_model.bin: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.71G/1.71G [00:13<00:00, 130MB/s]
C:\Users\Alienware\.conda\envs\MagicQuill\lib\site-packages\torch\_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
We will use 90% of the memory on device 0 for storing the model, and 10% for the buffer to avoid OOM. You can set `max_memory` in to a higher value to use more memory (at your own risk).
Loading checkpoint from: C:\MagicQuil\MagicQuill\models\checkpoints\SD1.5\realisticVisionV60B1_v51VAE.safetensors
model_type EPS
Using pytorch attention in VAE
Using pytorch attention in VAE
self.brushnet_loader.inpaint_files:  {'brushnet\\random_mask_brushnet_ckpt\\diffusion_pytorch_model.safetensors': 'C:\\MagicQuil\\MagicQuill\\models\\inpaint', 'brushnet\\segmentation_mask_brushnet_ckpt\\diffusion_pytorch_model.safetensors': 'C:\\MagicQuil\\MagicQuill\\models\\inpaint'}
BrushNet model file: C:\MagicQuil\MagicQuill\models\inpaint\brushnet\random_mask_brushnet_ckpt\diffusion_pytorch_model.safetensors
BrushNet model type: SD1.5
BrushNet model file: C:\MagicQuil\MagicQuill\models\inpaint\brushnet\random_mask_brushnet_ckpt\diffusion_pytorch_model.safetensors
BrushNet SD1.5 model is loaded
INFO: Could not find files for the specified pattern(s).
INFO:     Started server process [50088]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:7860 (Press CTRL+C to quit)
HTTP Request: GET https://api.gradio.app/pkg-version "HTTP/1.1 200 OK"

**Comment by zliucz** [comment]
I think the system is already running. Would you please check http://127.0.0.1:7860 to see if it works?
