### ISSUE TITLE
Can we make max_size=512 = set-able by user or 512 mandatory? Also can we save every generated image into outputs folder

### ISSUE THREAD

**Issue by FurkanGozukara** [magic-quill/MagicQuill#73]
In the Gradio APP atm it is hard-coded to resize into 512

Can you let user to change it in the Gradio interface if possible?

Or 512 is mandatory? thank you

I also don't see generated images are not saved anywhere. Can you auto save every generated image into outputs folder?

**Comment by zliucz** [comment]
Hi, there. Thanks for your interests on our project :). I've watched many of your videos, and many of them are inspiring.

Auto-resizing to 512 is not mandatory. You may check [issues#36](https://github.com/magic-quill/MagicQuill/issues/36). Your suggestion to let user change the resizing resolution is brilliant. We'll adjust it in our next update.

The generated images will not be saved automatically. You may click the download icon to manually download it.
![image](https://github.com/user-attachments/assets/a1a6fb7c-5ecc-48a7-9722-46ce0c5ee6c1)

**Comment by FurkanGozukara** [comment]
@zliucz can you add auto save? i certainly can fork and add but i really prefer to keep using your repo :) 

and thank you so much. both features are asked by many people to me

**Comment by zliucz** [comment]
Hi, there @FurkanGozukara. We have updated our code to implement these two features you've mentioned. Thank you again for your brilliant suggestions. Pull our latest code to try it out :).


![截屏2024-12-06 18 30 14](https://github.com/user-attachments/assets/51d5ecd5-9263-462f-b7fe-a5b4c978c192)

**Comment by FurkanGozukara** [comment]
@zliucz awesome ty

bigger res uses more vram though :D

do you think any quant or optimization possible?

![image](https://github.com/user-attachments/assets/ab791210-99c5-4370-b2bd-6f90552ad4fa)

**Comment by zliucz** [comment]
@FurkanGozukara Indeed. We have already applied 4bit-quantization to the Draw&Guess LLaVA. We'll look into possible optimization strategies :).
