### ISSUE TITLE
How can we have inbrowser and share = true? 

### ISSUE THREAD

**Issue by FurkanGozukara** [magic-quill/MagicQuill#77]
For example in other apps i make it like below

`demo.launch(share=args.share, inbrowser=True)`

in this one i tested and both failed

`app = gr.mount_gradio_app(app, demo, "/",inbrowser=True,share=True)`

`uvicorn.run(app, inbrowser=True,share=True)`

Thank you so much @zliucz 

This share especially important to make installer for RunPod and Massed Compute

**Comment by bruceyyu** [comment]
Hi @FurkanGozukara ! Unfortunately we use Fastapi for on-the-fly communication between the interface and model, the share=True is not supported (see here https://github.com/gradio-app/gradio/issues/1608).
To share your app, you may directly deploy it on HuggingFace space or your machine (https://www.gradio.app/guides/sharing-your-app)

**Comment by FurkanGozukara** [comment]
@bruceyyu that is very sad :( runpod and massed compute most commonly used ones 
 
i will look for alternative solution
