### ISSUE TITLE
Update Demo on HuggingFace to Support Resolution Adjustment

### ISSUE THREAD

**Issue by netrunner-exe** [magic-quill/MagicQuill#81]
Hello,

Thank you for your great work on this repository!

I noticed that the demo hosted on HuggingFace is still using an older version of the repository. The latest updates in the repo, including the Resolution Adjustment feature, are not yet reflected in the demo.

Could you please update the demo to match the current state of the repository so that users can access and test the new features? This would greatly enhance the usability and showcase the latest improvements.

Thank you in advance!

**Comment by zliucz** [comment]
Good suggestion :). We'll consider this. Thanks a lot.
