### ISSUE TITLE
 Gradio

### ISSUE THREAD

**Issue by Amark-cheey** [magic-quill/MagicQuill#86]
Could the author consider modifying Gradio to support zooming in on uploaded images? This would be helpful as some drawings are made using a brush, and it’s difficult to edit effectively on a small image

**Comment by zliucz** [comment]
We'll consider that. For now, try to use `cmd & +` or `ctrl & +` to zoom in the browser :).

**Comment by Amark-cheey** [comment]
![d561e0e1996c0c6d988ae89e609b5e4](https://github.com/user-attachments/assets/55da51ac-f41e-4d07-844b-1ee284828dc4)
When zooming in the browser, it looks like this, not enlarging the image.
