### ISSUE TITLE
How to fix  Some modules are dispatched on the CPU or the disk 

### ISSUE THREAD

**Issue by GitRhuddie** [magic-quill/MagicQuill#87]
(MagicQuill) E:\AIP\MagicQuill>python gradio_run.py
Total VRAM 2048 MB, total RAM 12156 MB
pytorch version: 2.1.2+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce 940MX : native
Using pytorch cross attention
['E:\\AIP\\MagicQuill', 'C:\\Users\\rhudd\\miniconda3\\envs\\MagicQuill\\python310.zip', 'C:\\Users\\rhudd\\miniconda3\\envs\\MagicQuill\\DLLs', 'C:\\Users\\rhudd\\miniconda3\\envs\\MagicQuill\\lib', 'C:\\Users\\rhudd\\miniconda3\\envs\\MagicQuill', 'C:\\Users\\rhudd\\miniconda3\\envs\\MagicQuill\\lib\\site-packages', '__editable__.llava-1.2.2.post1.finder.__path_hook__', 'E:\\AIP\\MagicQuill\\MagicQuill']
C:\Users\rhudd\miniconda3\envs\MagicQuill\lib\site-packages\huggingface_hub\file_download.py:797: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
We will use 90% of the memory on device 0 for storing the model, and 10% for the buffer to avoid OOM. You can set `max_memory` in to a higher value to use more memory (at your own risk).
Traceback (most recent call last):
  File "E:\AIP\MagicQuill\gradio_run.py", line 24, in <module>
    llavaModel = LLaVAModel()
  File "E:\AIP\MagicQuill\MagicQuill\llava_new.py", line 26, in __init__
    self.tokenizer, self.model, self.image_processor, self.context_len = load_pretrained_model(
  File "E:\AIP\MagicQuill\MagicQuill\LLaVA\llava\model\builder.py", line 117, in load_pretrained_model
    model = LlavaLlamaForCausalLM.from_pretrained(
  File "C:\Users\rhudd\miniconda3\envs\MagicQuill\lib\site-packages\transformers\modeling_utils.py", line 3790, in from_pretrained
    raise ValueError(
ValueError:
                        Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit
                        the quantized model. If you want to dispatch the model on the CPU or the disk while keeping
                        these modules in 32-bit, you need to set `load_in_8bit_fp32_cpu_offload=True` and pass a custom
                        `device_map` to `from_pretrained`. Check
                        https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu
                        for more details.

please help

**Comment by zliucz** [comment]
Unfortunately, your machine doesn't meet the minimum requirement to run the MagicQuill. Please use our free [online demo](https://huggingface.co/spaces/AI4Editing/MagicQuill). Thanks.
