### ISSUE TITLE
ModuleNotFoundError: No module named 'gradio_magicquill

### ISSUE THREAD

**Issue by icegurlkaija** [magic-quill/MagicQuill#88]
I'm getting this error trying to run it for first time and i'm not sure why

C:\Users\******\Documents\MagicQuill>python gradio_run.py
Traceback (most recent call last):
  File "C:\Users\*******\Documents\MagicQuill\gradio_run.py", line 5, in <module>
    from gradio_magicquill import MagicQuill
ModuleNotFoundError: No module named 'gradio_magicquill'

![imageyutgitu](https://github.com/user-attachments/assets/8d549cc4-dfb7-44de-a649-a91822748877)

--------------------------------------------------------------------------

**PLEASE READ BEFORE SUBMITTING AN ISSUE**  

MagicQuill is not a commercial software but a research project. While we strive to improve and maintain it, support is provided on a best-effort basis. Please be patient and respectful in your communications.
To help us respond faster and better, please ensure the following:  

1. **Search Existing Resources**: Have you looked through the documentation (e.g., hardware requirement and setup steps), and searched online for potential solutions?  
2. **Avoid Duplication**: Check if a similar issue already exists.  

If the issue persists, fill out the details below.

---

### **Checklist**

- [ ] I have searched the documentation and FAQs.  
- [ ] I have searched for similar issues but couldn’t find a solution.  
- [ ] I have provided clear and detailed information about the issue.  

---

### **Issue/Feature Request Description**

**Type of Issue:**  
- [ ] Bug  
- [ ] Feature Request  
- [ ] Question  

**Summary**:  
  

---

### **Steps to Reproduce (For Bugs Only)**  
1.  
2.  
3.  

**Expected Behavior**:  

**Actual Behavior**:  
  

---

### **Additional Context/Details**  

---

### **Environment**  
- **OS**:  
- **Version**:  
- **Any Relevant Dependencies**:  

---

### **Feature Request Specifics (If Applicable)**  
- **What problem does this solve?**:  
- **How will this feature improve the project?**:

**Comment by zliucz** [comment]
Check this [issue](https://github.com/magic-quill/MagicQuill/issues/71). Thanks.

**Comment by icegurlkaija** [comment]
> Check this [issue](https://github.com/magic-quill/MagicQuill/issues/71). Thanks.

i believe that worked, however i;mgetting this error now 

C:\Users\StrugglePC\Documents\MagicQuill>python gradio_run.py
Traceback (most recent call last):
  File "C:\Users\*****\Documents\MagicQuill\gradio_run.py", line 16, in <module>
    from MagicQuill.llava_new import LLaVAModel
  File "C:\Users\*****\Documents\MagicQuill\MagicQuill\llava_new.py", line 2, in <module>
    from transformers import TextStreamer
ModuleNotFoundError: No module named 'transformers'

**Comment by zliucz** [comment]
Please follow the setup guide at the Readme. Thanks.

**Comment by icegurlkaija** [comment]
> Please follow the setup guide at the Readme. Thanks.

Yes, Thank you. I must have missed a step or something because i used this prior but everything seems okay now. thank you for your time
