### ISSUE TITLE
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 90.00 MiB. GPU 0 has a total capacty of 6.00 GiB of which 0 bytes i emory 10.65 GiB is allocated by PyTorch, and 151.74 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is t_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

### ISSUE THREAD

**Issue by happydutch** [magic-quill/MagicQuill#90]
I am running out of memory, however the graphics card meets HW requirements. Any advice will be appreciated.

NVIDIA GeForce GTX 1660 (EVGA GeForce GTX 1660 XC Black Gaming, 6GB GDDR5, HDB Fan, 06G-P4-1161-KR)

![image](https://github.com/user-attachments/assets/b942f3fc-f6d2-4e2b-9d14-f113772b97b6)

**Comment by happydutch** [comment]
The graph shows memory usage before and after terminating the process.

**Comment by happydutch** [comment]
Never mind, lowering the resolution helps. Maybe it would be good to adjust it, as the default doesn't work with 6GB GPU.

**Comment by gowestin** [comment]
hi bro how you resolve above issue..im having same problem

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 90.00 MiB. GPU 0 has a total capacty of 6.00 GiB of which 0 bytes i emory 10.65 GiB is allocated by PyTorch, and 151.74 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is t_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
